# https://aka.ms/yaml
jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-18.04' # other options: 'macOS-10.13', 'VS2017-Win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.7'
      Python36:
        python.version: '3.6'
    maxParallel: 3

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: 'tox'
    displayName: 'Tox'
